Add-Type -AssemblyName System.Drawing
$img = [System.Drawing.Image]::FromFile('C:\Users\jerry\.gemini\antigravity\brain\19def5b0-546b-410b-9287-351a26769b8c\primora_icon_1774699447862.png')
$bmp = New-Object System.Drawing.Bitmap($img, 256, 256)
$iconStream = New-Object System.IO.MemoryStream
$writer = New-Object System.IO.BinaryWriter($iconStream)
$writer.Write([int16]0)
$writer.Write([int16]1)
$writer.Write([int16]1)
$writer.Write([byte]0)
$writer.Write([byte]0)
$writer.Write([byte]0)
$writer.Write([byte]0)
$writer.Write([int16]1)
$writer.Write([int16]32)
$msImg = New-Object System.IO.MemoryStream
$bmp.Save($msImg, [System.Drawing.Imaging.ImageFormat]::Png)
$writer.Write([int32]$msImg.Length)
$writer.Write([int32]22)
$writer.Write($msImg.ToArray())
$writer.Flush()
$iconBytes = $iconStream.ToArray()
[System.IO.File]::WriteAllBytes('c:\Users\jerry\OneDrive\Documents\DS4Windows\PrimoraApp\Resources\DS4W.ico', $iconBytes)
[System.IO.File]::WriteAllBytes('c:\Users\jerry\OneDrive\Documents\DS4Windows\PrimoraApp\Resources\DS4.ico', $iconBytes)
[System.IO.File]::WriteAllBytes('c:\Users\jerry\OneDrive\Documents\DS4Windows\PrimoraApp\Resources\DS4W - Black.ico', $iconBytes)
[System.IO.File]::WriteAllBytes('c:\Users\jerry\OneDrive\Documents\DS4Windows\PrimoraApp\Resources\DS4W - White.ico', $iconBytes)
