-- Create users table
CREATE TABLE public.users (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    license_tier TEXT NOT NULL DEFAULT 'Free',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for users
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own row"
    ON public.users FOR SELECT
    USING (auth.uid() = id);

CREATE POLICY "Users can update own row"
    ON public.users FOR UPDATE
    USING (auth.uid() = id);

-- Create profiles table
CREATE TABLE public.profiles (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    profile_name TEXT NOT NULL,
    controller_type TEXT NOT NULL,
    neuro_kinetic_config JSONB DEFAULT '{}'::jsonb NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profiles"
    ON public.profiles FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own profiles"
    ON public.profiles FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own profiles"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own profiles"
    ON public.profiles FOR DELETE
    USING (auth.uid() = user_id);

-- Create sync_log table
CREATE TABLE public.sync_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    action TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for sync_log
ALTER TABLE public.sync_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own sync_logs"
    ON public.sync_log FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own sync_logs"
    ON public.sync_log FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Marketplace profiles table
CREATE TABLE public.marketplace_profiles (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    creator_user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    creator_name TEXT NOT NULL DEFAULT '',
    profile_name TEXT NOT NULL,
    controller_type TEXT NOT NULL,
    description TEXT DEFAULT '',
    price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    download_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.marketplace_profiles ENABLE ROW LEVEL SECURITY;

-- Anyone can read marketplace listings
CREATE POLICY "Public can view marketplace profiles"
    ON public.marketplace_profiles FOR SELECT
    USING (true);

-- Only the creator can insert their own listings
CREATE POLICY "Creators can insert own listings"
    ON public.marketplace_profiles FOR INSERT
    WITH CHECK (auth.uid() = creator_user_id);

-- Only the creator can update their own listings
CREATE POLICY "Creators can update own listings"
    ON public.marketplace_profiles FOR UPDATE
    USING (auth.uid() = creator_user_id);

-- Only the creator can delete their own listings
CREATE POLICY "Creators can delete own listings"
    ON public.marketplace_profiles FOR DELETE
    USING (auth.uid() = creator_user_id);
